---
controller_organizations:
  - name: DevOps
  - name: Default
  
controller_user_accounts:
  - user: "rcalvaga"
    is_superuser: true
    password: "{{ admin_password }}"
  - user: "ansible"
    is_superuser: false
    password: "{{ user_password }}"
    
controller_projects:
  - name: GCE Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/gce-ansible.git
    scm_branch: master
    scm_clean: true
    description: GCE Project
    organization: Default
    wait: true
    update: true
  - name: Azure Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/azure-ansible.git
    scm_branch: master
    scm_clean: true
    description: Azure Project
    organization: Default
    wait: true
    update: true
  - name: AWS Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/aws-ansible.git
    scm_branch: master
    scm_clean: true
    description: AWS Project
    organization: Default
    wait: true
    update: true
    
  - credential_type: Machine
    organization: Default
    name: gce-machine-credentials
    description: This credential can be used with GCE instances
    inputs:
      username: azulman
      ssh_key_data: "{{ ssh_private_key }}"
    
