---
controller_organizations:
  - name: DevOps
  - name: Default
  
controller_user_accounts:
  - user: "rcalvaga"
    is_superuser: true
    password: "{{ admin_password }}"
  - user: "ansible"
    is_superuser: false
    password: "{{ user_password }}"
  - user: "azulman"
    is_superuser: false
    password: "{{ admin_password }}"
 
controller_projects:
  - name: GCE Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/gce-ansible.git
    scm_branch: master
    scm_clean: false
    description: GCE Project
    organization: "{{ organization }}"
    wait: true
    update: true
  - name: Azure Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/azure-ansible.git
    scm_branch: master
    scm_clean: false
    description: Azure Project
    organization: "{{ organization }}"
    wait: true
    update: true
  - name: AWS Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/aws-ansible.git
    scm_branch: master
    scm_clean: false
    description: AWS Project
    organization: "{{ organization }}"
    wait: true
    update: true
  - name: Ethermine Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/ethermine-ansible
    scm_branch: main
    scm_clean: false
    description: Ethermine Project
    organization: "{{ organization }}"
    wait: true
    update: true
  - name: Ansible Tower Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/tower-ansible
    scm_branch: master
    scm_clean: false
    description: Ansible Tower Project
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: KVM Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/libvirt-kvm-ansible
    scm_branch: master
    scm_clean: false
    description: KVM Project
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: Nessus Project
    scm_type: git
    scm_url: https://github.com/rcalvaga/tenable-nessus-ansible
    scm_branch: main
    scm_clean: false
    description: Nessus Project
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: RHEL7 Hardening
    scm_type: git
    scm_url: https://github.com/rcalvaga/rhel7-hardening-ansible
    scm_branch: main
    scm_clean: false
    description: RHEL7 Hardening
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: rhel7-pci-dss-hardening
    scm_type: git
    scm_url: https://github.com/rcalvaga/rhel7-pci-dss-hardening
    scm_branch: main
    scm_clean: false
    description: rhel7-pci-dss-hardening
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: ServiceNow-Project
    scm_type: git
    scm_url: https://github.com/mdelder/ansible-servicenow.git
    scm_branch: master
    scm_clean: false
    description: ServiceNow-Project
    organization: "{{ organization }}"
    wait: true
    update: true 
  - name: Windows Update
    scm_type: git
    scm_url: https://github.com/rcalvaga/ansible-role-windows_update
    scm_branch: master
    scm_clean: false
    description: Windows Update
    organization: "{{ organization }}"
    wait: true
    update: true 

controller_credential_types:
- name: KVM Server Credential Type
  description: KVM Server Credential Type
  inputs:
    fields:
    - id: kvm_username
      type: string
      label: KVM Server Username
    - id: kvm_password
      type: string
      label: KVM Server Password
      secret: true
    required:
    - kvm_username
    - kvm_password
  injectors:
    extra_vars:
      kvm_password: !unsafe '{{ kvm_password }}'
      kvm_username: !unsafe '{{ kvm_username }}'
      
controller_credentials:
  - name: AWS Credentials
    description: AWS Credentials
    organization: "{{ organization }}"
    credential_type: Amazon Web Services
    inputs:
      username: "{{ aws_access_key }}"
      password: "{{ aws_secret_key }}"

  - name: KVM Server Credentials
    description: KVM Server Credentials
    organization: "{{ organization }}"
    credential_type: KVM Server Credential Type
    inputs:
      kvm_username: "{{ kvm_username }}"
      kvm_password: "{{ kvm_password }}"
      
  - name: Azure Credentials
    description: Azure Credentials
    organization: "{{ organization }}"
    credential_type: Microsoft Azure Resource Manager
    inputs:
      subscription: "{{ azure_subscription_id }}"
      client: "{{ azure_client_id }}"
      secret: "{{ azure_secret }}"
      tenant: "{{ azure_tenant }}"
      
  - name: GCE Credentials
    description: GCE Google Credentials
    organization: "{{ organization }}"
    credential_type: Google Compute Engine
    inputs:
      username: "{{ gce_account_email }}"
      project: "{{ gce_project }}"
      ssh_key_data: "{{ gce_ssh_key_data }}"
      
controller_inventories:
  - name: AWS Inventory
    organization: "{{ organization }}"
    description: AWS Inventory
    
  - name: Azure Inventory
    organization: "{{ organization }}"
    description: Azure Inventory
    
  - name: GCE Inventory
    organization: "{{ organization }}"
    description: GCE Inventory
    
controller_inventory_sources:
  - name: AWS Source
    source: ec2
    inventory: AWS Inventory
    credential: AWS Credentials
    description: created using Ansible controller collections
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    
  - name: Azure Source
    source: azure_rm
    inventory: Azure Inventory
    credential: Azure Credentials
    description: created using Ansible controller collections
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    
controller_templates:
  - name: Azure - Create Resource Group
    organization: "{{ organization }}"
    execution_environment: Ansible Engine 2.9 execution environment
    job_type: run
    inventory: Demo Inventory
    project: Azure Project
    playbook: azure-cfme-ansible-create-resourcegroup.yml
    credentials:
    - Azure Credentials
    survey: {}
    extra_vars:
      resourcegroup: Test
      location: centralus
      storageaccount: teststorageaccount2326
      virtualnetwork: TestNetwork
      address_prefix: 10.0.0.0/16
      subnet: TestSubnet
      subnet_prefix: 10.0.0.0/24
    ask_variables_on_launch: yes
    
  - name: Azure - Delete Resource Group
    organization: "{{ organization }}"
    execution_environment: Ansible Engine 2.9 execution environment
    job_type: run
    inventory: Demo Inventory
    project: Azure Project
    playbook: azure-cfme-ansible-delete-resourcegroup.yml
    credentials:
    - Azure Credentials
    survey: {}
    extra_vars:
      resourcegroup: Test
      location: centralus
      storageaccount: teststorageaccount2326
      virtualnetwork: TestNetwork
      address_prefix: 10.0.0.0/16
      subnet: TestSubnet
      subnet_prefix: 10.0.0.0/24
    ask_variables_on_launch: yes

  - name: KVM - Create VMs KVM Libvirt
    organization: "{{ organization }}"
    description: KVM - Create VMs KVM Libvirt
    execution_environment: Ansible Engine 2.9 execution environment
    job_type: run
    inventory: KVM Inventory
    project: KVM Project
    playbook: tower-ansible-create-vm-libvirt.yml
    limit: kvm-nodes
    verbosity: 3
    become_enabled: yes
    credentials:
    - KVM Credentials
    survey: {}
    extra_vars:
      vm_location: "/var/lib/libvirt/images"
      root_pass: "Redhat1!"
      guests:
        test:
        mem: 512
        cpus: 1
        template_name: centos-7.4  
        hostname: test1.localdomain  
        os_type: centos7.0
        file_type: qcow2