---
- name: Playbook to configure Ansible Controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_validate_certs: false
  collections:
    - ansible.controller
    - infra.aap_configuration
