---
- name: Playbook to configure ansible controller post installation
  hosts: all
  vars_files:
    - ../vaults/all.yml
  connection: local
  collections:
    - awx.awx
    - infra.aap_configuration
  tasks:
    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
